# Generated by Django 5.1.4 on 2025-07-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='forncedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
