# Generated by Django 5.1.4 on 2025-07-10 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motopecas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='forncedor',
            new_name='Fornecedor',
        ),
    ]
