# Generated by Django 5.2.2 on 2025-07-22 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motopecas', '0003_cliente_pagamento_produto_servico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='motopecas.fornecedor'),
        ),
        migrations.AlterField(
            model_name='pedidoproduto',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='motopecas.pedido'),
        ),
        migrations.AlterField(
            model_name='pedidoproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='motopecas.produto'),
        ),
        migrations.AlterField(
            model_name='vendaitem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='motopecas.produto'),
        ),
        migrations.AlterField(
            model_name='vendaitem',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='motopecas.vendaproduto'),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='motopecas.cliente'),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='motopecas.pagamento'),
        ),
        migrations.AlterField(
            model_name='vendaservico',
            name='pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='motopecas.pagamento'),
        ),
    ]
